/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7cd854cc-fc6e-4848-bb18-306737596ccd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_P790AqNEN",
    "aws_user_pools_web_client_id": "7c3a0b8vgl2vnos9ip5v1gnn38",
    "oauth": {}
};


export default awsmobile;
